[package]
name = "rust_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
colored  = "2"
tetra = "0.7"
log = "0.4"

[env]
RUST_LOG="info"

[profile.release]
debug = true